#!/bin/bash

# mpdnotification modified to not be a service and be active when I click music module or press the shortcut
if [ "$MPD_HOST" ]; then HOST="$MPD_HOST"; else HOST="localhost"; fi
if [ "$MPD_PORT" ]; then PORT="$MPD_PORT"; else PORT="6600"; fi
MPD_TCP="/dev/tcp/$HOST/$PORT"
coverDir=$HOME/.local/share/covers
expireTime=3300

mpd_sndcommmand() {
	# $1 command
	! exec 5<> $MPD_TCP 2>/dev/null && return 1
#	[[ $? -gt 0 ]] && return 1
	echo "$1" >&5
	echo "close" >&5
	tmp=$(cat <&5)
	exec 5>&-
	_ret=$(head -n -1 <<< "$tmp" | tail -n +2)
	return 0
}

mpd_getinfo() {
	! mpd_sndcommmand currentsong && return 1
	#[[ $? -gt 0 ]] && return 1
	_tmp=$_ret
	mpdTitle=$(grep "^Title: " <<< "$_tmp" 2>/dev/null | sed "s/Title: //")
	mpdArtist=$(grep "^Artist: " <<< "$_tmp" 2>/dev/null | sed "s/Artist: //")
	mpdAlbum=$(grep "^Album: " <<< "$_tmp" 2>/dev/null | sed "s/Album: //")
	_songtime=$(grep "^Time: " <<< "$_tmp" 2>/dev/null | sed "s/Time: //" | cut -f 1 -d :)
	(( _mm=_songtime / 60 ))
	[[ ${#_mm} -eq 1 ]] && _mm="0$_mm"
	(( _ss=_songtime - _mm * 60 ))
	[[ ${#_ss} -eq 1 ]] && _ss="0$_ss"
	mpdLength="$_mm:$_ss"
	mpd_sndcommmand "status"
	_tmp=$_ret
	mpdSongID=$(grep "^songid: " <<< "$_tmp" 2>/dev/null | sed "s/songid: //")
	mpdPlaylistL=$(grep "^playlistlength: " <<< "$_tmp" 2>/dev/null | sed "s/playlistlength: //")
}

handle_event() {
	mpd_getinfo
	mpdAlbum="${mpdAlbum//&/&amp;}"
	mpdTitle="${mpdTitle//&/&amp;}"
	mpdArtist="${mpdArtist//&/&amp;}"
#	[[ "${#mpdArtist}" -gt "25" ]] && mpdArtist=$(echo "${mpdArtist:0:25}...")
#	[[ "${#mpdTitle}" -gt "25" ]] && mpdTitle=$(echo "${mpdTitle:0:25}...")
#	[[ "${#mpdAlbum}" -gt "25" ]] && mpdAlbum=$(echo "${mpdAlbum:0:25}...")
	notify-send --expire-time="${expireTime}" -i "$coverDir/$mpdAlbum" "$mpdTitle" "\By: <b><i>${mpdArtist}</i></b>
Album: <u><i>${mpdAlbum}</i></u>
Length: <i>${mpdLength}</i>
Position: <i>${mpdSongID} / ${mpdPlaylistL}</i>"
}

handle_event
