#!/bin/sh

# Shows the current moon phase.
# Signal 17

moonfile="${XDG_DATA_HOME:-$HOME/.local/share}/moonphase"

{ [ "$(stat -c %y "$moonfile" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && [ -s "$moonfile" ] ;} ||
	{ curl -sf "wttr.in/?format=%m" > "$moonfile" || exit 1 ;}
	#{ curl -sf "wttr.in/?format=%m" || echo "⚠️" ;} > "$moonfile"

icon="$(cat "$moonfile")"

case "$icon" in
	🌑) name="New" ;;
	🌒) name="Waxing Crescent" ;;
	🌓) name="First Quarter" ;;
	🌔) name="Waxing Gibbous" ;;
	🌕) name="Full" ;;
	🌖) name="Waning Gibbous" ;;
	🌗) name="Last Quarter" ;;
	🌘) name="Waning Crescent" ;;
	*) exit 1 ;;
esac

echo "${icon-?}"

case $BLOCK_BUTTON in
	1) notify-send "$icon $name" ;;
	3) notify-send "🌜 Moon phase module" "<i>Displays current moon phase.</i>
- 🌑: New
- 🌒: Waxing Crescent
- 🌓: First Quarter
- 🌔: Waxing Gibbous
- 🌕: Full
- 🌖: Waning Gibbous
- 🌗: Last Quarter
- 🌘: Waning Crescent" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
