#!/bin/sh

# Music module
# Signal 11
#filter() { mpc | sed "/^volume:/d;s/\\[paused\\].*//g;/\\[playing\\].*/d;0,/^/{s/^/& /}" | paste -sd ' ' -;}
# can it work with mpc current??
filter="$(mpc | sed "/^volume:/d;s/\\[paused\\].*//g;/\\[playing\\].*/d;0,/^/{s/^/& /}" | paste -sd ' ' -;)"
onlytitle() { mpc --format %title% | sed "/^volume:/d;s/\\[paused\\].*//g;/\\[playing\\].*/d;0,/^/{s/^/& /}" | paste -sd ' ' -;}

pidof -x sb-mpdup >/dev/null 2>&1 || sb-mpdup >/dev/null 2>&1 &

#[ "$(filter | wc -m)" -gt 45 ] && onlytitle || filter
[ "${#filter}" -gt 45 ] && onlytitle || echo "$filter"

case $BLOCK_BUTTON in
	1) mpc -q toggle ;;	# right click, pause/unpause
	2) setsid -f "$TERMINAL" -e ncmpcpp -qs visualizer ;;  # middle click, music player
	3) mpdnoti ;;		# notification with album cover
	4) mpc -q next ;;	# scroll down, next
	5) mpc -q prev ;;	# scroll up, previous
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
