#!/bin/sh

#Checks if random mode is on
[ "$(mpc | tail -n 1 | awk '{ printf $6 }')" = "on" ] && ran=🔀 || ran=🔁
# Single
[ "$(mpc | tail -n 1 | awk '{ printf $8 }')" = "on" ] && con=🧍 || con=🥦
# Consumer mode
[ "$(mpc | tail -n 1 | awk '{ printf $10 }')" = "on" ] && con=🍔 || con=🥦

#[ "$(mpc | tail -n 1 | awk '{ printf $10 }')" = "on" ] && echo 🍔 || echo 🍎
echo "$ran$con"
case $BLOCK_BUTTON in
	1) mpc random ;;	# on/off
	2) mpc sinlge ;;	# on/off
	3) mpc consume ;;	# on/off
#	2) setsid -f "$TERMINAL" -e ncmpcpp -s visualizer ;;  # right click, pause/unpause
#	3) mpdnoti ;;		# Notification with album cover(time 0.10)
	#4) mpc prev   | filter ;;  # scroll up, previous
	#5) mpc next   | filter ;;  # scroll down, next
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
# TODO how to make this only appear when sb-music is updated?
