#!/bin/sh

# Music module
# Signal 11

icon=" "
name="$(mpc current --format '[[%artist% - ]%title%]|[%file%]')"
shortname="$(mpc current --format '[%title%]|[%file%]')"

# don't print anything if nothing is playing
[ "$(mpc status '%state%')" = 'paused' ] && echo '' && exit

[ "${#name}" -gt 45 ] && printf '%s%s\n' "$icon" "$shortname" || printf '%s%s\n' "$icon" "$name"

case $BLOCK_BUTTON in
	1) mpc -q toggle ;;	# right click, pause/unpause
	2) setsid -f "$TERMINAL" -e ncmpcpp -qs visualizer ;;  # middle click, music player
	3) mpdnoti ;;		# notification with album cover
	4) mpc -q next ;;	# scroll down, next
	5) mpc -q prev ;;	# scroll up, previous
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
