#!/bin/sh

# syncthing icon if it's running
# Signal 10

{ pidof -q syncthing && echo "🌐" ;} || exit

case $BLOCK_BUTTON in
	1) killall syncthing && kill -55 "$(pidof dwmblocks)" ;;
	3) notify-send "🌐 Syncthing module" "\-Shows 🌐 if syncthing is running.
- Left click to kill syncthing
- Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
