#!/bin/sh

# Originally by Andr3as07 <https://github.com/Andr3as07>
# Some changes by Luke

# This block displays the number running background tasks.  Requires tsp.

tspout="$(ts -l)"

# Handle mouse clicks
case $BLOCK_BUTTON in
	1) echo "$tspout" > "${XDG_CACHE_HOME:-$HOME/.cache}/tspout"
	setsid -f "$TERMINAL" -e less "${XDG_CACHE_HOME:-$HOME/.cache}/tspout"	;;
	2) ts -C	;; # Middle click
	3) notify-send "Tasks module" "🤖: number of running/queued background tasks
- Left click opens tsp
- Middle click cleans tsp"	;; # Right click
	4) $TERMINAL -e $EDITOR "$0" ;;
esac

numr=$(echo "$tspout" | grep -c "running")
numq=$(echo "$tspout" | grep -c "queued")

num=$((numr + numq))

[ "$num" -gt 0 ] && echo "📝$num($numq)"
#[ "$num" -gt 0 ] && echo "🤖$num($numq)" || echo ""
