#!/bin/sh

# Signal 10
# Prints the current volume or 🔇 if muted.
case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	3) notify-send "Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.- Scroll to change." ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo '🔇' && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "20" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon$vol%"
