#!/bin/sh

# Displays number of upgradeable packages using xbps-install
# package manager. Void linux
# You can change to update on the background by changing the 9 line:
# 1) sudo xbps-install -Suy && notify-send "Void Updated";;

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e sudo xbps-install -uv ;;
	2) notify-send "Packages" "$(xbps-install -un | cut -d' ' -f1 | sort | uniq)" ;;
	3) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

packages=$(xbps-install -Sun | cut -d' ' -f2 | sort | uniq -c | xargs)
# -u:	lists all upgreadeable packages
# -n:	'raw', it shows what it does without doing it?
[ -z "$packages" ] && echo "" || echo "📦$packages""s"
