#!/usr/bin/env sh
export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"

# this should work with both local and global ueberzug install
#if [ ! -x $(command -v ueberzug >/dev/null 2>&1) ]; then
#	vifm
#	exit
#fi
[ ! -x "$(command -v ueberzug 2>&1)" ] && vifm && exit

cleanup() {
    rm "$FIFO_UEBERZUG" 2>/dev/null	# this doesn't exist?
    pkill -P $$ 2>/dev/null
}
#cleanup() {
#    rm "$FIFO_UEBERZUG"	# this doesn't exist?
#    pkill -P $$
#}
pkill -P $$ 2>/dev/null
rm "$FIFO_UEBERZUG" 2>/dev/null
mkfifo "$FIFO_UEBERZUG" >/dev/null
trap cleanup EXIT 2>/dev/null
#tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash 2>&1 >/dev/null &
tail --follow "$FIFO_UEBERZUG" | ueberzug layer -sp bash >/dev/null 2>&1 &

vifm "$@"
cleanup
