#!/bin/bash

# If cachedir does not exist, create it
#cachedir="/tmp/walldown"
cachedir=/tmp/redyt	# this directory so sxiv goes into 9 tag(uncoment the otherone)
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"
tagoptions="minimalism\nCyberpunk 2077\nfantasy girl\ndigital art\nanime\nnature\n4K"

if [ -z "$1" ]; then
	# Ask the user to enter a wallhaven
	query=$(echo -e "$tagoptions" | dmenu -p "Search Wallhaven: " -i)
	[ -z "$query" ] && exit 	# If nothing was chosen, exit
# Otherwise assign the first argument to the query
else
	query="$1"
fi

sortoptions="random\ndate_added\nrelevance\nviews\nfavorites\ntoplist"
sorting=$(echo -e "$sortoptions" | dmenu -p "Sort Order: " -i)
[ -z "$sorting" ] && exit

query="${query/ */+}"
notify-send "Walldown" "📩Downloading wallpapers🌋\n⏳Queuing..."

# Set your resolution here
res=1920x1080
maxpage=4
for i in $(seq 1 $maxpage);
do
  #curl -s https://wallhaven.cc/api/v1/search\?atleast\=1920x1080\&sorting\=$sorting\&q\=$query\&page\=$i > tmp.txt
	curl -s https://wallhaven.cc/api/v1/search\?atleast\=$res\&sorting\=$sorting\&q\=$query\&page\=$i > $cachedir/tmp.json
	page=$(jq '.' < $cachedir/tmp.json | grep -Eoh "https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b")
	wget -nc -P $cachedir $page
done

notify-send "Walldown" "👍 Download Finished⌛, Enjoy! 🍵"
sxiv -abp -s f $cachedir/*
rm "$cachedir"/*
