#!/bin/sh

menu(){
    printf "1. [URL]   Shorten url✂️\n"
    printf "2. [URL]   Download file📥\n"
    printf "3. [URL]   Download yt audio🎧\n"
    printf "4. [URL]   Play videos/audio in mpv🤟🎥\n"
    printf "5. [URL]   Save as bookmark📑\n"
    printf "6. [Image] Save clipbaord image🔖\n"
    printf "7. [Shell] Run shell command on st🤖\n"
}
spell_failed(){
notify-send "Error 404🤖"
exit 1
}

# 'c' or 'clipboard'
prompt=$(xclip -o -sel c | tr -d '\n')
# Check if clipboard has something
[ "$prompt" = "" ] && notify-send "Empty clipboard📎" && exit
[ "${#prompt}" -gt 30 ] && prompt="${prompt%"${prompt#?????????????????????????}"}"..."${prompt#"${prompt%???????}"}" || prompt="$prompt"
choice=$(menu | dmenu -p "$prompt" -i -l 20 | cut -d. -f1)
cbtext=$(xclip -o -selection clipboard)

case $choice in
    1)
	notify-send "Cutting...✂️"
	output=$(curl -s -F"shorten=$cbtext" 0x0.st)
	[ "$output" = "Segmentation fault" ] && spell_failed
	echo "$output" | xclip -sel c
	notify-send "Shorten Link is in Clipboard" "<i>$output</i>"
	;;
    2)
	qndl "$cbtext" || spell_failed	;;
    3)
	qndl "$cbtext" 'audio' || spell_failed	;;
    4)
	mpv "$cbtext" || spell_failed	;;
    5)
	bookmenu "$cbtext"	;;
    6)
	xclip -sel clipboard -t image/png -o > "$HOME"/Pictures/Saved/"$(date +'%Y_%m_%d_%I_%M_%p')".png || spell_failed	;;
    7)
	st -e "$cbtext" || spell_failed	;;
esac
