#!/bin/bash

cache_dir=$HOME/.local/share/clipmenu
cache_size=200
mkdir -p -m0700 "$cache_dir"

declare -A last_data

while sleep 1; do
  if type -p xsel >/dev/null 2>&1; then
    data=$(xsel --clipboard; printf x)
  else
    data=$(xclip -o -sel clipboard; printf x)
  fi

  # We add and remove the x so that trailing newlines are not stripped.
  # Otherwise, they would be stripped by the very nature of how POSIX
  # defines command substitution.
  data=${data%x}

  [[ $data == *[^[:blank:]]* ]] || continue

  [[ $last_data == "$data" ]] && continue
  last_data=$data

  md5=$(md5sum <<< "$data")
  md5=${md5%% *}

  if
    [[ $(ls "$cache_dir" | wc -l) == $cache_size ]]
  then
    rm "$cache_dir/"`ls -t $cache_dir | tail -n -1`
  fi

  printf '%s' "$data" > "$cache_dir/$(LC_ALL=C date +%F-%H-%M-%S)-$md5"
done
