#!/bin/sh

menu(){
    printf "1. [URL]   Shorten url✂️\n"
    printf "2. [URL]   Download file📥\n"
    printf "3. [URL]   Play videos in mpv🎥\n"
    printf "4. [URL]   Play audio in mpv🎧\n"
    printf "5. [Image] Save clipbaord image🔖\n"
    printf "6. [Shell] This will run any shell command🤖\n"
    printf "7. [URL]   Save as bookmark📑\n"
}

spell_failed(){
    notify-send "Failed to cast spell"
}
bookmarkfile=${XDG_CONFIG_HOME:-"$HOME/.config"}/bookmarks
prompt=$(xclip -o -sel clipboard | tr -d '\n')
# Check if clipboard has something
[ "$prompt" = "" ] && notify-send "Empty clipboard📎" && exit
[ "${#prompt}" -gt 30 ] && prompt="${prompt%"${prompt#????????????????????}"}"..."${prompt#"${prompt%???????}"}" || prompt="$prompt"
choice=$(menu | dmenu -p "$prompt" -i -l 20 | cut -d. -f1)
cbtext=$(xclip -o -selection clipboard)



case $choice in
    1)
	notify-send "Cutting...✂️"
	output=$(curl -s -F"shorten=$cbtext" 0x0.st)
	if [ "$output" = "Segmentation Fault" ]; then
	    spell_failed
	else
	    echo "$output" | xclip -sel c
	    notify-send "Shorten Link is in Clipboard" "$output"
	fi
	break
	;;
    2)
	wget -P ~/Downloads $cbtext && notify-send "Downloading File" || spell_failed
	break
	;;
    3)
	mpv "$cbtext" || spell_failed
	break
	;;
    4)
	mpv "$cbtext" || spell_failed
	break
	;;
    5)
	file=$(date +"%Y_%m_%d_%I_%M_%p")
	xclip -selection clipboard -t image/png -o > $HOME/Pictures/Saved/$file.png || spell_failed
	break
	;;
    6)
	$cbtext || spell_failed
	break
	;;
esac
