#!/bin/sh

# The famous "get a menu of emojis to copy" script.
# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 "$XDG_DATA_HOME"/emoji | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
[ -n "$1" ] && xdotool type "$chosen"
[ -z "$1" ] && printf '%s' "$chosen" | xsel -b -l /tmp/.xsel && notify-send "'$chosen' copied to clipboard."
# Find a way if no matching results exit 🤔

#[ -n "$1" ] && xdotool type "$chosen" || printf '%s' "$chosen" | xsel -b -l /tmp/.xsel && notify-send "'$chosen' copied to clipboard."
##if [ -n "$1" ]; then
##	xdotool type "$chosen"
##else
##	#echo "$chosen" | tr -d '\n' | xclip -selection clipboard
##	echo "$chosen" | tr -d '\n' | xs
##	notify-send "'$chosen' copied to clipboard." &
##fi

