#!/bin/bash

# Formats a notification with mpd metadata (which should be the song metadata).
# Also, displays the image cover of the current song album: this image cover
# needs to have the same name as the album in the song, and the extension can
# be .png, .jpg or .jpeg. If no matches, uses $coverDir/sample.png as the image.

# Dep: mpd, mpc

# Where the image file covers are searched
coverDir="${HOME}/.local/share/covers"

# first argument, else this hardcoded value: how much time does the
# notification stays (in ms)
expireTime=${1:-3300}

mpdTitle="$(mpc current --format '[%title%]|[%file%]')"
mpdArtist="$(mpc current --format '%artist%')"
mpdAlbum="$(mpc current --format '%album%')"
mpdLength="$(mpc current --format '%artist%')"
mpdSongID="$(mpc current --format '%id%')"
mpdPlaylist="$(mpc | awk 'FNR == 2 {print $2}' | sed 's,.*/,,')"

# bash magik
shopt -s nullglob extglob
Files=("$coverDir"'/'"${mpdAlbum}"@(.png|.jpg|.jpeg))
IconPath=${Files[0]:-"$coverDir"/sample.png}

notify-send \
	--replace-id=101 \
	--app-name=mpdnoti \
	--expire-time="${expireTime}" \
	--icon "$IconPath" \
	"$mpdTitle" \
"By: <b><i>${mpdArtist}</i></b>
Album: <u><i>${mpdAlbum}</i></u>
Length: <i>${mpdLength}</i>
Position: <i>${mpdSongID} / ${mpdPlaylist}</i>"
