#!/bin/sh

# Formats a notification with useful info about the song file and mpd. Displays
# the image cover of the current song album. The image file cover needs to have
# the same name as the album in the song, WITHOUT ANY EXTENSION
# (no .png or .jpg).
# mpdnoti expiretime # first argument as the expire time

# Dep: mpd, mpc

# Where the image file covers are searched
coverDir=$HOME/.local/share/covers

# how much time does the notification stays (in ms)
expireTime=${1:-3300}

mpdTitle="$(mpc current --format '[%title%]|[%file%]')"
mpdArtist="$(mpc current --format '%artist%')"
mpdAlbum="$(mpc current --format '%album%')"
mpdLength="$(mpc current --format '%artist%')"
mpdSongID="$(mpc current --format '%id%')"
mpdPlaylist="$(mpc | awk 'FNR == 2 {print $2}' | sed 's,.*/,,')"

notify-send \
	--expire-time="${expireTime}" \
	--icon "$coverDir/$mpdAlbum" \
	"$mpdTitle" \
"\By: <b><i>${mpdArtist}</i></b>
Album: <u><i>${mpdAlbum}</i></u>
Length: <i>${mpdLength}</i>
Position: <i>${mpdSongID} / ${mpdPlaylist}</i>"
