#!/bin/sh

# This removes all possible metadata on a image
# First argument is the file/regex

# remove all exif (probably there are none)
exif -all= "$1" && exif -gps:all= "$1"
# remove all medata (may resolution)
mogrify -strip "$1"
