#!/bin/sh
#notify-send -t 2400 "Keyboard remapping⌨️ " "WAIT!\nRerunning <b>customs</b> shorcuts"

# altgr variant to be able to have arrow keys on vim key when pressed
setxkbmap -layout us -variant altgr-intl -option nodeadkeys -option caps:backspace
# setxkbmap -device 10 -option caps:backspace
# setxkbmap -option caps:backspace	# Caps to backspace
xset r 66		# Capslock key with rate
xset r rate 300 50	# Increase key speed via a rate change

# alt with vimkeys to arrowkeys and more
[ -f "$HOME/.bash/keys" ] && xmodmap "$HOME/.bash/keys"
