#!/usr/bin/env bash
readonly ID_PREVIEW="preview"

# I removed the inc and dec functions and pdf page variable,
# if you want to take a look at the second page better off opening
# zathura because it takes long and its buggy
# PD: of course I don't need that "feature"
#
PLAY_GIF="yes"
# By enabling this option the GIF will be animated, by leaving it commented like it
# is now will make the gif previews behave the same way as video previews.

#AUTO_REMOVE="yes"
# By enabling this option the script will remove the preview file after it is drawn
# and by doing so the preview will always be up-to-date with the file.
# This however, requires more CPU and therefore affects the overall performance.
# I think that doen't work, if it does its really the same for me
PDF_FILE_CONFIG="${XDG_CACHE_HOME:-$HOME/.cache/}/vifmimg/vifmimgpdffile"
PDF_FILE=""
# cache on home dir scructure so it keeps after boots?(if you dont have the same images consistently then uncomment the tmp one
cachedir="${XDG_CACHE_HOME:-$HOME/.cache/}/vifmimg"
#cachedir="/tmp/vifmimg"

# Initialize the variable and required files
[ -f "$PDF_FILE_CONFIG" ] && PDF_FILE=$(cat "$PDF_FILE_CONFIG") || touch "$PDF_FILE_CONFIG"

# Create temporary(now in cache) working directory if the directory structure doesn't exist
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"

previewclear() {
    declare -pA cmd=([action]=remove [identifier]="$ID_PREVIEW") > "$FIFO_UEBERZUG"
}

fileclean() {
   if [[ -f "$cachedir/$6.png" ]]; then
        rm -f "${cachedir:?}/$6.png"
    elif  [[ -d "$cachedir/$6/" ]]; then
        rm -rf "${cachedir:?}/$6/"
     fi
}

preview() {
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
	# how to make this work with the cachedir
        [path]="$PWD/$6") \
        > "$FIFO_UEBERZUG"
}

previewvideo() {
[ ! -f "$cachedir/$6.png" ] && ffmpegthumbnailer -i "$PWD/$6" -o "$cachedir/$6.png" -s 0 -q 10
	declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="$cachedir/$6.png") \
        > "$FIFO_UEBERZUG"
}

previewepub() {
[ ! -f "$cachedir/$6.png" ] && epub-thumbnailer "$6" "$cachedir/$6.png" 1024
	declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="$cachedir/$6.png") \
        > "$FIFO_UEBERZUG"
}

previewaudio() { # Do i need this?
[ ! -f "$cachedir/$6.png" ] && ffmpeg -i "$6" "$cachedir/$6.png" -y &> /dev/null
  declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                     [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                     [path]="$cachedir/$6.png") \
		     > "$FIFO_UEBERZUG"
}

previewfont() { # what is this one?
[ ! -f "$cachedir/$6.png" ] && fontpreview -i "$6" -o "$cachedir/$6.png"
declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                     [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                     [path]="$cachedir/$6.png") \
			> "$FIFO_UEBERZUG"
}

previewgif() {
[ ! -d "$cachedir/$6/" ] && mkdir -p "$cachedir/$6/" ; convert -coalesce "$PWD/$6" "$cachedir/$6/$6.png"
					# use find?
[ -n "$PLAY_GIF" ] &&
	for frame in $(ls -1 $cachedir/$6/$6*.png | sort -V); do
        	declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
			[path]="$frame") \
			> "$FIFO_UEBERZUG"
            # Sleep between frames to make the animation smooth.
	    # Make it infinite loop on gif?
        		sleep .07
        done
#  if you commented out then just view
[ -z "$PLAY_GIF" ] && declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                	[path]="$cachedir/$6/$6-0.png") \
                	> "$FIFO_UEBERZUG"
}
#
# Okay you have to choose between png or jpg funtions
#
previewpdf() { #jpg ("faster")
[ ! "$6" == "$PDF_FILE" ] && rm -f "$cachedir/$6"

[ ! -f "$cachedir/$6.jpg" ] && pdftoppm -f 1 -l 1 -scale-to-y -1 -singlefile -jpeg -tiffcompression jpeg "$6" "$cachedir/$6"

# instead of file why not variables?...
echo "$6" > "$PDF_FILE_CONFIG"

declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        	[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
		[path]="$cachedir/$6.jpg") \
        	> "$FIFO_UEBERZUG"
}

#previewpdf() { #png (fatter)
#	# Should it convert the pdf-file to jpg or png? (jpg is faster!)
#	# PDF_PATH: The temporary path where the image is saved
#	if [ "$7" == "png" ]; then
#		PDF_TYPE="png"
#		PDF_PATH="$cachedir/$6.png"
#	else
#		PDF_TYPE="jpg"
#		PDF_PATH="$cachedir/$6"
#	fi
#
#[ ! "$6" == "$PDF_FILE" ] && rm -f "${cachedir:?}"/$6
#
#[ ! -f "$PDF_PATH.$PDF_TYPE" ] &&
#	[ $PDF_TYPE == "jpg" ] &&
#	pdftoppm -f 1 -l 1 -scale-to-y -1 -singlefile -jpeg -tiffcompression jpeg "$6" "$PDF_PATH"
#
#echo "$6" > "$PDF_FILE_CONFIG"
#
#declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
#        	[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
#		[path]="$PDF_PATH.$PDF_TYPE") \
#        	> "$FIFO_UEBERZUG"
#}

previewmagick() { #is this one faster then normal?, maybe just lowering the resolution??
[ ! -f "$cachedir/$6.png" ] && convert -thumbnail "$(identify -format "%wx%h" "$6")" "$PWD/$6" "$cachedir/$6.png"
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="$cachedir/$6.png") \
        > "$FIFO_UEBERZUG"
}

main() {
    case "$1" in
        "clear") previewclear "$@" ;;
        "clean") fileclean "$@" ;;
        "draw") preview "$@" ;;
        "videopreview") previewvideo "$@" ;;
        "epubpreview") previewepub "$@" ;;
        "gifpreview") previewgif "$@" ;;
        "pdfpreview") previewpdf "$@" ;;
        "magickpreview") previewmagick "$@" ;;
        "audiopreview") previewaudio "$@" ;;
        "fontpreview") previewfont "$@" ;;
        *) echo "Unknown command: '$@'" ;;
    esac
}
main "$@"
