#!/usr/bin/env sh

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"
#export FIFO_UEBERZUG="${XDG_CACHE_HOME:-$HOME/.cache/}/vifmimg/vifm-ueberzug-${PPID}"

#[ ! -n "$DISPLAY" ] || [ ! -x $(command -v ueberzug >/dev/null 2>&1) ]
[ ! -x "$(command -v ueberzug 2>&1)" ] && vifm "$@" && exit 1

[ -e "$FIFO_UEBERZUG" ] || { mkfifo "$FIFO_UEBERZUG" || exit 1 ; }
ueberzug layer --parser json --silent < "$FIFO_UEBERZUG" &
exec 3>"$FIFO_UEBERZUG"

vifm "$@"

exec 3>&-
rm "$FIFO_UEBERZUG" > /dev/null 2>&1
