#!/bin/sh

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"
#export FIFO_UEBERZUG="${XDG_CACHE_HOME:-$HOME/.cache/}/vifmimg/vifm-ueberzug-${PPID}"

# tty
[ -z "$DISPLAY" ] && vifm "$@" && exit

# only run if ueberzug installed
! command -v ueberzug && vifm "$@" && exit 1

[ -e "$FIFO_UEBERZUG" ] || { mkfifo "$FIFO_UEBERZUG" || exit 1 ;}
ueberzug layer --parser json --silent < "$FIFO_UEBERZUG" &
exec 3>"$FIFO_UEBERZUG"

vifm "$@"

exec 3>&-
rm "$FIFO_UEBERZUG" > /dev/null 2>&1
