#!/bin/sh

# Requires Luke Smith tag wrapper script with some tweak.

[ ! -d "$1" ] && printf "Please add a directory to tagg.\\n" && exit

#Prompts
echo "Enter the album title:"; read -r album
echo "Enter the artist:"; read -r author
echo "Enter the publication year:"; read -r year

# List of all songs on a directory
find "$1" -maxdepth 1 -type f -printf '%f\n' > songs.txt
while read -r song;
do
	file="$1"/"$song"
	# Use the name of the file as the title
	title="$(noextname "$song")"
	tag -a "$author" -A "$booktitle" -t "$title" -d "$year" "$file" && echo "Tagging... '$song'✔️"
done < songs.txt && rm songs.txt

# Rename the directory to the album name
escbook="$(echo "$booktitle" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr ' ' '_' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
# If the name is the same as the recommenden one then dont rename it??
mv "$1" "$escbook"
