#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download

# Default directory used to store the feed file and fetched images
cachedir=/tmp/rss
# If cachedir does not exist, create it
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"

case "$1" in
	*mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*)
		setsid -f vlc "$1" >/dev/null 2>&1
		;;
	*png|*jpg|*jpe|*jpeg|*JPG|*gif|*.webp)
		curl -sL "$1" > "$cachedir/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" && sxiv -abp -s f "$cachedir"/*  >/dev/null 2>&1 && rm "${cachedir:?}"/*
		;;
	*pdf|*cbz|*cbr)
		curl -sL "$1" > "$cachedir/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" && zathura "$cachedir/$(echo "$1" | sed "s/.*\///;s/%20/ /g")"  >/dev/null 2>&1 && rm "${cachedir:?}"/*
 		;;
	*mp3|*flac|*opus|*mp3?source*)
		qndl "$1" 'curl -LO'  >/dev/null 2>&1
		;;
	*)
	[ -f "$1" ] && setsid -f "$TERMINAL" -e "$EDITOR" "$1" >/dev/null 2>&1 ||
	[ "${#1}" -gt 30 ] && visual="${1%"${1#????????????????????}"}"..."${1#"${1%???????}"}" || visual="$1"
	[ "$(printf "Yes\\nNo" | dmenu -i -p "Open on Browser=>$visual?")" = "Yes" ] >/dev/null 2>&1 && "$BROWSER" "$1" >/dev/null 2>&1 && xdotool key super+2 && notify-send "Opening on browser🦊..."
esac
