#!/bin/bash

# Get the names right

for fullpath in "$@"
do
    filename="${fullpath##*/}"				# Strip longest match of */ from start
    dir="${fullpath:0:${#fullpath} - ${#filename}}"	# Substring from 0 thru pos of filename
    base="${filename%.[^.]*}"				# Strip shortest match of . plus at least one non-dot char from end
    ext="${filename:${#base} + 1}"			# Substring from len of base thru end
    if [[ -z "$base" && -n "$ext" ]]; then		# If we have an extension and no base, it's really the base
        base=".$ext"
        ext=""
    fi

    #echo -e "$fullpath:\n\tdir  = \"$dir\"\n\tbase = \"$base\"\n\text  = \"$ext\""
   # echo "$ext"
done
case "$1" in
	-f) echo "$fullpath"	;;
	-d) echo "$dir"		;;
	-b) echo "$base"	;;
    -h | --help)
        echo "noextname"
        echo
        echo "Syntax: noextname [-f|-d|-b|-h|--help]"
        echo "options:"
        echo "-f     Print the full path of the file"
        echo "-d     Print the directory the file is in"
        echo "-b     Print the name of the file without the file extension"
        echo "-h     Print this Help."
        echo "--help     Print this Help."
        echo
        ;;
	*)  echo "noextname"
        echo
        echo "Syntax: noextname [-f|-d|-b|-h|--help]"
        echo "options:"
        echo "-f     Print the full path of the file"
        echo "-d     Print the directory the file is in"
        echo "-b     Print the name of the file without the file extension"
        echo "-h     Print this Help."
        echo "--help     Print this Help."
        echo
		;;
esac

