#!/bin/sh

# Spawns dmenu with a big font and red color if your battery is bellow %5
# percent (or the percent you wish). Usefull because dmenu gets the focus
# (stdin) and allows me to get the battery. Run this as a cronjob, add it to
# sb_battery, etc.
# A good patch for dmenu would be center..

# dmenu will 'prompt' this message
msg="%5 or less battery!"
# where the 'helper' file is store
bat_file="${XDG_DATA_HOME:-$HOME}/.bat_alarm"
# change BAT number to whatever you have
bat=/sys/class/power_supply/BAT0

[ "$(cat $bat/status)" = "Charging" ] && exit

if [ "$(cat $bat/capacity)" -lt 5 ]; then
	# if the file doesn't exist then make it (if it doesn't exist then it's
	# the first time running..)
	[ ! -f "$bat_file" ] && echo 0 > "$bat_file"

	# if the file has 0 then run it, else it already has runned
	[ "$(cat "$bat_file")" = "0" ] && printf | dmenu -p "$msg" -fn Monospace-20 -nb "dark red" -nf white -sb red -sf black
fi
