#!/bin/sh

# Check if necessary programs are installed
#for prog in dmenu jq sxiv; do
#[ ! "$(which "$prog")" ] && echo "Please install $prog!" && exit 1
#done
# If notify-send is not installed, use echo as notifier
[ ! "$(which notify-send)" ] && notifier="echo" || notifier="notify-send"

# Default config directory
configdir="${XDG_CONFIG_HOME:-$HOME/.config}/redyt"
# Create .config/redyt if it does not exist to prevent
# the program from not functioning properly
[ ! -d "$configdir" ] && echo "Directory $configdir does not exist, creating..." && mkdir -p "$configdir"

# Default subreddit that will be inserted in "subreddit.txt"
# if it does not exist
defaultsub="linuxmemes"

# If subbreddit.txt does not exist, create it to prevent
# the program from not functioning properly
[ ! -f "$configdir/subreddit.txt" ] && echo "$defaultsub" >> "$configdir/subreddit.txt"

# If no argument is passed
if [ -z "$1" ]; then
	# Ask the user to enter a subreddit
	# reddit colors
	colors="-nb #FF5700 -nf #CEE3F8 -sb #FF8b60 -sf #FF4500"
	subreddit=$(dmenu $colors -p "Select Subreddit r/" -i -l 10 < "$configdir/subreddit.txt" | cut -d\| -f1 | awk '{$1=$1;print}')

	# If no subreddit was chosen, exit
	[ -z "$subreddit" ] && exit 1

# Otherwise assign the first argument to the
# subreddit variable
else
	subreddit="$1"
fi

# Default directory used to store the feed file and fetched images
cachedir="/tmp/redyt"

# If cachedir does not exist, create it
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"

# Limit the maximum number of requests to make
limit=100

# Send a notification
$notifier "Redyt" "📩 Downloading your 🤡Memes\n⏳Queuing..."

# Download the subreddit feed, containing only the
# first 100 entries (limit), and store it inside
# cachedir/tmp.json
curl -H "User-agent: 'your bot 0.1'" "https://www.reddit.com/r/$subreddit/hot.json?limit=$limit" > "$cachedir/tmp.json"

# Create a list of images
imgs=$(jq '.' < "$cachedir/tmp.json" | grep url_overridden_by_dest | grep -Eo "http(s|)://.*(jpg|png)\b" | sort -u)

# If there are no images, exit
[ -z "$imgs" ] && $notifier "Redyt" "sadly, there are no images for subreddit $subreddit, please try again later!😥" && exit 1

kill -37 $(pidof dwmblocks)	# task module bar
# Download images to $cachedir (use task spooler)
ts -nf wget -P "$cachedir" $imgs

# Send a notification
$notifier  "Redyt" "👍 Download Finished⌛, Enjoy! 😊"

# Display the images
sxiv -abp -s f "$cachedir"/*

# Once finished, remove all of the cached images
rm "${cachedir:?}"/*
