#!/bin/sh

# Lists the files inside the currently active window (non recursively,
# -maxdepth 1) using dmenu
# Opens it using xdg-open since are local files

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
PID="$(pstree -lpA "$PID" | tail -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"
#xdg-open "$(find "$(readlink /proc/"$PID"/cwd)" -maxdepth 1 -type f | sed "s|$HOME|~|g" | dmenu -i -l 30 "$@" )" || return 1
cd "$(readlink /proc/"$PID"/cwd)" || return 1
xdg-open "$(find . -maxdepth 1 -type f -printf "%f\n" | sort | dmenu -i -l 30 "$@" )" || notify-send ""
