#!/bin/sh

# Lists the files inside the currently active window (non recursively,
# -maxdepth 1) using dmenu

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
PID="$(pstree -lpA "$PID" | tail -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')"
#linkhandler "$(readlink -f "$(ls "$(readlink /proc/"$PID"/cwd)" | dmenu -i -l 30 "$@" )")" || return 1
#xdg-open "$(find "$(readlink /proc/"$PID"/cwd)" -maxdepth 1 -type f  | dmenu -i -l 30 "$@" )" || return 1
xdg-open "$(find "$(readlink /proc/"$PID"/cwd)" -maxdepth 1 -type f | sed "s|$HOME|~|g" | dmenu -i -l 30 "$@" )" || return 1
