#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
#case "$(readlink -f /sbin/init)" in
#	*runit*) hib="sudo -A zzz" ;;
#	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
#esac
 #${hib:-systemctl suspend-then-hibernate -i}
# 🔒 lock		slock

cmds="\
ﯥ Screen off	xset dpms force off
💀 Shutdown	sudo shutdown -h now
🛌 Suspend	sudo zzz
🔃 Reboot	sudo reboot
🚪leave dwm	kill -TERM $(pgrep -u $USER "\bdwm$")
♻ renew dwm	kill -HUP $(pgrep -u $USER "\bdwm$")"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1
eval "$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-)"
