#!/bin/sh

# Variables
# youtube colors
colors="-nb black -nf white -sb #E62117 -sf black -i -l 15"
guicmd=dmenu		#or use "rofi -dmenu -i"
promptcmd=fzf
# Why you wanna tell google you use linux?
user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0'
#user_agent='your bot 0.1'
cachedir=/tmp/termyt	#for images and description
#task=tsp		#task spooler

# Help
help_opt() {
	#Check if necessary programs are installed
	for Dep in mpv youtube-dl fzf dmenu; do
		if ! command -v "$Dep" 1>/dev/null; then
			printf "%s not found. Please install it.\n\n" "$Dep"
		fi
	done
	printf "Usage:\n"
	printf "\ttermyt				asks for input in stdin using fzf\n"
	printf "\ttermyt <search query>		takes input from the passed query using fzf\n"
	printf "\ttermyt -r			takes input and prompts using dmenu/rofi\n"
	printf "\ttermyt -t			After selecting the video, the thumbnails displays on sxiv\n"
	printf "\ttermyt -T <quality>		Downloads thumbsnail for the query, by default on the worse quality so it downloads quickly.\n"
	printf "\t				Possible values are: max - hq - mid - low\n"
}
thumb_dl() { # only one thumbnail, the selected one, before watching the video was the first use of this
	# check cache directory
	[ ! -d "$cachedir" ] && mkdir -p "$cachedir"
	curl -sL "$img/$id/$res" > "$cachedir"/"$id".jpg && sxiv -abp -s f "$cachedir"/"$id".jpg
	rm "${cachedir:?}"/*
}

choose() {
	echo "Choose Video/Playlist to play: "
	choice=$(printf '%s' "$ids" | cut -d'	' -f2 | $promptcmd)	# dont show id
	[ -z "$choice" ] && exit					# if esc-ed then exit
	id=$(printf '%s' "$ids" | grep -Fwm1 "$choice" | cut -d'	' -f1) # get id of choice
}

thumball() { # 30 thumbnails
	# check cache directory
	[ ! -d "$cachedir" ] && mkdir -p "$cachedir"
	echo "$ids" | awk '{print $1}' | sed "s,^,&$img/,;s,$,&/$res," > "$cachedir"/thumb.txt
	while read -r URL; do
		var=$((var + 1))
	curl -L "$URL" > "$cachedir"/"$(printf '%s' "$ids" | sed "${var}q;d" | cut -d'	' -f2 | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr ' ' '_' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")".jpg
	done < $cachedir/thumb.txt
	notify-send "Finished⌛" && sxiv -bpt -s f $cachedir/*
	rm "${cachedir:?}"/*
}

# Handle options
while getopts ":h :g :r :t :T:" opt; do
    case $opt in
	h)
	help_opt && exit 1	;;
	r)
	query=$(echo | "$guicmd" $colors -p "🔎 Search: ")
	promptcmd="$guicmd $colors -p Video:"
	#notifier=notify-send
	[ -z "$query" ] && exit 1	;;
	t)
	thumb=1
	res="maxresdefault.jpg"	;;
	T)
	thumball=1
	case "${@:$OPTARG}" in
		max) res="maxresdefault.jpg" ;;
		hq)  res="hqdefault.jpg" ;;
		mid) res="mqdefault.jpg" ;;
		low) res="sddefault.jpg" ;;
		*) echo "Valid arguments are: max - hq - mid - low" && help_opt && exit 1
	esac
	;;
	#[ "$OPTARG" = " " ] && help_opt && exit 1
	#d) #Get description with youtube-dl
	#description=1
	#;;
	?)
	echo "Error! Invalid option!" && help_opt && exit 1 ;;
    esac
done
# Removes all the options that have been parsed by getopts from the parameters
# list, and so after that point, $1 will refer to the first non-option argument
# passed to the script.
shift "$((OPTIND-1))"

[ -z "$query" ] && if [ -z "$*" ]; then
	printf '%s' " Search: "
	read -r query
else
	query="$*"
	printf '%s' "Searching..."
fi
[ -z "$query" ] && exit

# sanitise the query
query=$(echo "$query" | sed \
	-e 's|+|%2B|g'\
	-e 's|#|%23|g'\
	-e 's|&|%26|g'\
	-e 's| |+|g')
[ -z "$query" ] && exit

# fetch the results with the $query and delete all escaped characters
response="$(curl "https://www.youtube.com/results" -s -G --user-agent "$user_agent" --data-urlencode "search_query=$query" -H 'authority: www.youtube.com' -H 'accept-language: en-US,en;q=0.9' -L --compressed | sed 's|\\.||g')"

# if unable to fetch the youtube results page, inform and exit (posix?)
[ -z "$response" ] && print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[0m\n" && exit 1

# regex expression to match video and playlist entries from yt result page
vgrep='"videoRenderer":{"videoId":"\K.{11}".+?"text":".+?[^\\](?=")'
pgrep='"playlistRenderer":{"playlistId":"\K.{34}?","title":{"simpleText":".+?[^\"](?=")'
# grep the id and title
# return them in format id (type) title
getresults() {
	printf '%s' "$response" | grep -oP "$1" |\
		awk -F\" -v p="$2" '{ print $1 "\t" p " " $NF}'
}
# get the list of videos/playlists and their ids in videoids and playlistids
videoids=$(getresults "$vgrep")
playlistids=$(getresults "$pgrep" "(playlist)")
# if there are playlists or videos, append them to list
[ -n "$playlistids" ] && ids="$playlistids\n"
[ -n "$videoids" ] && ids="$ids$videoids"
# url prefix for videos and playlists
video_link="https://youtu.be/"
play_link="https://youtube.com/playlist?list="

# Display thumbnail on sxiv
img="http://img.youtube.com/vi"


#[ -n $description ] && youtube-dl "https://www.youtube.com/results?search_query=$query" --get-description >> "$cachedir"/description.TXT && setsid -f "$TERMINAL" -e less "$cachedir"/description.TXT
[ -z "$thumb" ] && choose
[ -n "$thumb" ]  && choose && thumb_dl
[ -n "$thumball" ] && notify-send "Youtube📼" "Fetching all thumbnails\nPlease wait⏳..." && thumball && choose #&& dmeurl "$videolink$id"

# The 'choice' variable as a second argument is to display it on a notification
# with dmenurl. Replace dmenurl with mpv
[ "${#id}" -ge 11 ] && dmenurl "$video_link$id" "$(echo "$choice" | sed 's/ *//')"
[ "${#id}" -ge 34 ] && dmenurl "$play_link$id" "$(echo "$choice" | sed 's/ *//')"
